/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blueconsul;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class MenuKonselingUser extends javax.swing.JFrame {

    /**
     * Creates new form menu_konseling
     */
    
    private String role_id;
    private String user_id;
    
    public void setRoleId(String id) {
        role_id = id;
    }
    
    public String getRoleId() {
        return role_id;
    }
    
    public void setUserId(String id) {
        user_id = id;
    }
    
    public String getUserId() {
        return user_id;
    }
    
    public MenuKonselingUser(String name, String role_id, String user_id) {
        setUserId(user_id);
        setRoleId(role_id); 
        initComponents();
        username_label.setText(name);
        showListKonsulType();
    }
    
    private void showListKonsulType() { 
        try {
            DefaultListModel model = new DefaultListModel();
            konsul_type_list.setModel(model);
            int row = konsul_type_list.getModel().getSize();
            for (int i = 0; i < row; i++) {
               model.removeElement(0);
            }
            Connection cn = new Connection();
            ResultSet rs = cn.Select("select * from konsul_type");
            while(rs.next()) {
                model.addElement(rs.getString(2));
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    };
    
    private void showListKonsulTermAndCondition(String value) {
        try {
            Connection cn = new Connection();
            ResultSet rs = cn.Select("select konsul_term_and_condition.term_and_condition from konsul_term_and_condition, konsul_type where konsul_term_and_condition.id_konsul_type = konsul_type.id and konsul_type.konsul_type='"+value+"'");
            while(rs.next()) {
                term_and_condition_textfield.setText(rs.getString(1));
                term_and_condition_textfield.setEditable(false);
            }  
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        NotSatisfiedButton = new javax.swing.JButton();
        SatisfiedButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        term_and_condition_textfield = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        konsul_type_list = new javax.swing.JList<>();
        ChooseKonsulButton = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel8.setText("0888-888-888");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        username_label.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        username_label.setText("Username");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueconsul/admin.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueconsul/ask.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setText("0888-888-888");

        jButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        NotSatisfiedButton.setBackground(new java.awt.Color(255, 255, 204));
        NotSatisfiedButton.setText("Tidak Puas");
        NotSatisfiedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotSatisfiedButtonActionPerformed(evt);
            }
        });

        SatisfiedButton.setBackground(new java.awt.Color(255, 255, 204));
        SatisfiedButton.setText("Puas");
        SatisfiedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatisfiedButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(term_and_condition_textfield);

        konsul_type_list.setBackground(new java.awt.Color(255, 255, 204));
        konsul_type_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cuti", "Finansial", "EQ" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(konsul_type_list);

        ChooseKonsulButton.setText("Pilih");
        ChooseKonsulButton.setToolTipText("");
        ChooseKonsulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseKonsulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(SatisfiedButton)
                .addGap(35, 35, 35)
                .addComponent(NotSatisfiedButton)
                .addGap(88, 88, 88))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ChooseKonsulButton, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChooseKonsulButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SatisfiedButton)
                    .addComponent(NotSatisfiedButton))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NotSatisfiedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotSatisfiedButtonActionPerformed
        // TODO add your handling code here:
          try {
            Connection cn = new Connection();
            String selected = konsul_type_list.getSelectedValue();
            System.out.println(selected);
            if (selected == null) {
                JOptionPane.showMessageDialog(null, "Pilih Jenis Konsul Terlebih Dahulu");
                return;
            }
            ResultSet rs = cn.Select("select konsul_type.id from konsul_type where konsul_type.konsul_type='"+selected+"'");
            while(rs.next()) {
             ResultSet rs2 = cn.Select("select * from konsul_satisfied where id_konsul_type="+rs.getString(1)+" and is_satisfied='no'");
              if (rs2.next()) {
                  this.dispose();
                  new QuestionBoxUser(username_label.getText(), getRoleId(), getUserId()).setVisible(true);
              } else {
                  cn.Insert("insert into konsul_satisfied(users_id,id_konsul_type,is_satisfied) values('" + getUserId() + "'," +rs.getString(1)+ ",'"+"no"+"')");
                  this.dispose();
                  new QuestionBoxUser(username_label.getText(), getRoleId(), getUserId()).setVisible(true);
              }   
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_NotSatisfiedButtonActionPerformed

    private void SatisfiedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatisfiedButtonActionPerformed
        // TODO add your handling code here:
           try {
            Connection cn = new Connection();
            String selected = konsul_type_list.getSelectedValue();
            if (selected == null) {
                JOptionPane.showMessageDialog(null, "Pilih Jenis Konsul Terlebih Dahulu");
                return;
            }
            ResultSet rs = cn.Select("select konsul_type.id from konsul_type where konsul_type.konsul_type='"+selected+"'");
            while(rs.next()) {
             ResultSet rs2 = cn.Select("select * from konsul_satisfied where id_konsul_type="+rs.getString(1)+" and is_satisfied='yes'");
              if (rs2.next()) {
                  this.dispose();
                  new DashboardUser(username_label.getText(), getRoleId(), getUserId()).setVisible(true);
              } else {
                  cn.Insert("insert into konsul_satisfied(users_id,id_konsul_type,is_satisfied) values('" + getUserId() + "'," +rs.getString(1)+ ",'"+"yes"+"')");
                  this.dispose();
                  new DashboardUser(username_label.getText(), getRoleId(), getUserId()).setVisible(true);
              }   
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SatisfiedButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DashboardUser(username_label.getText(), getUserId(), getRoleId()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChooseKonsulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseKonsulButtonActionPerformed
        // TODO add your handling code here:
        String selected = konsul_type_list.getSelectedValue();
        showListKonsulTermAndCondition(selected);
    }//GEN-LAST:event_ChooseKonsulButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKonselingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKonselingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKonselingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKonselingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKonselingUser("","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseKonsulButton;
    private javax.swing.JButton NotSatisfiedButton;
    private javax.swing.JButton SatisfiedButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> konsul_type_list;
    private javax.swing.JEditorPane term_and_condition_textfield;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
